ApiBundle\Entity\Projects:
    type: entity
    table: projects
    oneToMany:
      ProjectSubjects:
            targetEntity: Subjects
            mappedBy: SubjectProject
    manyToOne:
      ProjectUsers:
        targetEntity: Users
        inversedBy: UsersProjects
        joinColumn:
            name: created_by
            referencedColumnName: id
    repositoryClass: ApiBundle\Repository\ProjectsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks:
        prePersist: [ insertCreatedAtAuto, insertUpdateAtAuto ]
    fields:
        name:
            type: string
        description:
            type: string
        active:
            type: boolean
            option:
                defaults: 1
        created_at:
            type: datetime
        update_at:
            type: datetime
        begin_at:
            type: datetime
        end_at:
            type: datetime
