ApiBundle\Entity\Subjects_team:
    type: entity
    table: subjects_team
    manyToOne:
      SubjectTeam:
        targetEntity: Team_details
        inversedBy: TeamSubject
        joinColumn:
            name: team_id
            referencedColumnName: id
      TeamSubjectDetails:
        targetEntity: Subjects
        inversedBy: SubjectTeamDetails
        joinColumn:
            name: subject_id
            referencedColumnName: id
    repositoryClass: ApiBundle\Repository\Subjects_teamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks:
        prePersist: [ insertCreatedAtAuto, insertUpdateAtAuto ]
    fields:
        active:
            type: boolean
            option:
                defaults: 1
        created_at:
            type: datetime
        update_at:
            type: datetime