ApiBundle\Entity\Tokens_transaction:
    type: entity
    table: tokens_transaction
    manyToOne:
      TokenSubjects:
        targetEntity: Subjects
        inversedBy: SubjectTokens
        joinColumn:
            name: subject_id
            referencedColumnName: id
      TokenTeams:
        targetEntity: Team_details
        inversedBy: TeamTokens
        joinColumn:
            name: team_id
            referencedColumnName: id
      TransactionTokenCoatchUsers:
        targetEntity: Users
        inversedBy: UsersCoatchTransactionToken
        joinColumn:
            name: coatch_id
            referencedColumnName: id
    repositoryClass: ApiBundle\Repository\Tokens_transactionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks:
        prePersist: [ insertCreatedAtAuto, insertUpdateAtAuto ]
    fields:
        howmany:
            type: integer
        active:
            type: boolean
            option:
                defaults: 1
        created_at:
            type: datetime
        update_at:
            type: datetime
