ApiBundle\Entity\Users:
    type: entity
    table: users
    oneToMany:
      UsersTeam:
            targetEntity: Users_team
            mappedBy: TeamUsers
      UsersProjects:
            targetEntity: Projects
            mappedBy: ProjectUsers
      UsersSubjects:
            targetEntity: Subjects
            mappedBy: SubjectUsers
      UsersCoatch:
            targetEntity: Subjects_coatch
            mappedBy: CoatchUsers
      UsersCoatchTransactionToken:
            targetEntity: Tokens_transaction
            mappedBy: TransactionTokenCoatchUsers
    repositoryClass: ApiBundle\Repository\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks:
        prePersist: [ insertCreatedAtAuto, insertUpdateAtAuto ]
    fields:
        firstname:
            type: string
        lastname:
            type: string
        email:
            type: string
        role:
            type: integer
        active:
            type: boolean
            option:
                defaults: 1
        created_at:
            type: datetime
        update_at:
            type: datetime
